const setting = {
  read: 'list_general_setting',
  update: 'update_general_setting',
};
const client = {
  read: 'show_client',
  list: 'list_client',
};
const item = {
  read: 'show_item',
  create: 'create_item',
  update: 'update_item',
  delete: 'delete_item',
  list: 'list_item',
};
const branch = {
  read: 'show_branch',
  create: 'create_branch',
  update: 'update_branch',
  delete: 'delete_branch',
  list: 'list_branch',
};
const employee = {
  read: 'show_employee',
  create: 'create_employee',
  update: 'update_employee',
  delete: 'delete_employee',
  list: 'list_employee',
};
const order = {
  read: 'show_order',
  create: 'create_order',
  update: 'update_order',
  list: 'list_order',
  changeStatus: 'change_status_order',
  changeEmployee: 'change_employee_order',
  createPayment: 'create_payment_order',
  updatePayment: 'update_payment_order',
  updateImage: 'update_image_order',
  showJobOrder: 'show_job_order',
  updateJobOrder: 'update_job_order',
};
const role = {
  read: 'show_role',
  create: 'create_role',
  update: 'update_role',
  delete: 'delete_role',
  list: 'list_role',
};
const car = {
  read: 'show_car',
  create: 'create_car',
  update: 'update_car',
  delete: 'delete_car',
  list: 'list_car',
};
const position = {
  read: 'show_position',
  create: 'create_position',
  update: 'update_position',
  delete: 'delete_position',
  list: 'list_position',
};
const referral = {
  read: 'show_referral',
  create: 'create_referral',
  update: 'update_referral',
  delete: 'delete_referral',
  list: 'list_referral',
};

const transfer = {
  read: 'show_item',
  create: 'create_item',
  update: 'update_item',
  delete: 'delete_item',
  list: 'list_item',
};

const dashboard = {
  read: 'dashboard',
};

const internalPurchase = {
  list: 'list_internal_purchase_item',
  create: 'create_internal_purchase',
  update: 'update_internal_purchase',
  delete: 'delete_internal_purchase',
};

const reports ={
  list: 'list_report',
}

export const permissions = {
  setting,
  client,
  item,
  branch,
  employee,
  order,
  role,
  car,
  position,
  referral,
  dashboard,
  transfer,
  internalPurchase,
  reports
};

export const usePermission = () => {
  const userPermissions = JSON.parse(localStorage.getItem('userPermissions'));
  const haveAccess = permission => {
    if (userPermissions && userPermissions.length > 0) {
      return userPermissions?.includes(permission);
    }
    return false;
  };

  return { haveAccess };
};

export const colorList = [
  { name: 'Cloud Burst', value: '#202e54' },
  { name: 'Sunset Orange', value: '#fd5e53' },
  { name: 'Turquoise', value: '#40e0d0' },
  { name: 'Lawn Green', value: '#7cfc00' },
  { name: 'Goldenrod', value: '#daa520' },
  { name: 'Deep Pink', value: '#ff1493' },
  { name: 'Dodger Blue', value: '#1e90ff' },
  { name: 'Dark Orchid', value: '#9932cc' },
  { name: 'Salmon', value: '#fa8072' },
  { name: 'Khaki', value: '#f0e68c' },
  { name: 'Tomato', value: '#ff6347' },
  { name: 'Royal Blue', value: '#4169e1' },
  { name: 'Firebrick', value: '#b22222' },
  { name: 'Sienna', value: '#a0522d' },
  { name: 'Plum', value: '#dda0dd' },
  { name: 'Peru', value: '#cd853f' },
  { name: 'Dark Slate Gray', value: '#2f4f4f' },
  { name: 'Light Salmon', value: '#ffa07a' },
  { name: 'Medium Violet Red', value: '#c71585' },
  { name: 'Orchid', value: '#da70d6' },
  { name: 'Peach Puff', value: '#ffdab9' },
  { name: 'Powder Blue', value: '#b0e0e6' },
  { name: 'Rosy Brown', value: '#bc8f8f' },
  { name: 'Slate Blue', value: '#6a5acd' },
  { name: 'Steel Blue', value: '#4682b4' },
  { name: 'Thistle', value: '#d8bfd8' },
  { name: 'Wheat', value: '#f5deb3' },
  { name: 'Yellow Green', value: '#9acd32' },
  { name: 'Medium Slate Blue', value: '#7b68ee' },
  { name: 'Indian Red', value: '#cd5c5c' },
  { name: 'Medium Aquamarine', value: '#66cdaa' },
  { name: 'Medium Sea Green', value: '#3cb371' },
  { name: 'Medium Turquoise', value: '#48d1cc' },
  { name: 'Moccasin', value: '#ffe4b5' },
  { name: 'Navajo White', value: '#ffdead' },
  { name: 'Olive Drab', value: '#6b8e23' },
  { name: 'Pale Goldenrod', value: '#eee8aa' },
  { name: 'Pale Green', value: '#98fb98' },
  { name: 'Pale Turquoise', value: '#afeeee' },
  { name: 'Pale Violet Red', value: '#db7093' },
  { name: 'Papaya Whip', value: '#ffefd5' },
  { name: 'Sea Green', value: '#2e8b57' },
  { name: 'Sky Blue', value: '#87ceeb' },
  { name: 'Spring Green', value: '#00ff7f' },
  { name: 'Tan', value: '#d2b48c' },
  { name: 'Violet', value: '#ee82ee' },
  { name: 'Yellow', value: '#ffff00' },
  { name: 'Azure', value: '#f0ffff' },
  { name: 'Beige', value: '#f5f5dc' },
  { name: 'Coral', value: '#ff7f50' },
  { name: 'Crimson', value: '#dc143c' },
  { name: 'Cyan', value: '#00ffff' },
  { name: 'Dark Blue', value: '#00008b' },
  { name: 'Dark Cyan', value: '#008b8b' },
  { name: 'Dark Goldenrod', value: '#b8860b' },
  { name: 'Dark Gray', value: '#a9a9a9' },
  { name: 'Dark Green', value: '#006400' },
  { name: 'Dark Khaki', value: '#bdb76b' },
  { name: 'Dark Magenta', value: '#8b008b' },
  { name: 'Dark Olive Green', value: '#556b2f' },
  { name: 'Dark Orange', value: '#ff8c00' },
  { name: 'Dark Red', value: '#8b0000' },
  { name: 'Dark Salmon', value: '#e9967a' },
  { name: 'Dark Sea Green', value: '#8fbc8f' },
  { name: 'Dark Slate Blue', value: '#483d8b' },
  { name: 'Gold', value: '#ffd700' },
  { name: 'Green Yellow', value: '#adff2f' },
  { name: 'Light Coral', value: '#f08080' },
  { name: 'Light Cyan', value: '#e0ffff' },
  { name: 'Light Goldenrod Yellow', value: '#fafad2' },
  { name: 'Light Green', value: '#90ee90' },
  { name: 'Light Pink', value: '#ffb6c1' },
  { name: 'Light Steel Blue', value: '#b0c4de' },
  { name: 'Medium Orchid', value: '#ba55d3' },
  { name: 'Medium Purple', value: '#9370db' },

  // Added essential car colors
  { name: 'Black', value: '#000000' },
  { name: 'White', value: '#ffffff' },
  { name: 'Silver', value: '#c0c0c0' },
  { name: 'Gray', value: '#808080' },
  { name: 'Gunmetal', value: '#2a3439' },
  { name: 'Charcoal', value: '#36454f' },
  { name: 'Ivory', value: '#fffff0' },
  { name: 'Burgundy', value: '#800020' },
  { name: 'Champagne', value: '#f7e7ce' },
  { name: 'Navy', value: '#000080' },
  { name: 'Graphite', value: '#383838' },
  { name: 'Bronze', value: '#cd7f32' },
  { name: 'Copper', value: '#b87333' },
  { name: 'Pearl White', value: '#fefefa' },
  { name: 'Matte Black', value: '#1c1c1c' },
  { name: 'Forest Green', value: '#228b22' },
];


// 
// "dashboard",
//   "list_general_setting",
//   "update_general_setting",
//   "show_client",
//   "list_client",
//   "show_item",
//   "create_item",
//   "update_item",
//   "delete_item",
//   "list_item",
//   "show_branch",
//   "create_branch",
//   "update_branch",
//   "delete_branch",
//   "list_branch",
//   "show_employee",
//   "create_employee",
//   "update_employee",
//   "delete_employee",
//   "list_employee",
//   "create_order",
//   "update_order",
//   "list_order",
//   "show_order",
//   "show_job_order",
//   "update_job_order",
//   "change_status_order",
//   "change_employee_order",
//   "create_payment_order",
//   "update_payment_order",
//   "update_image_order",
//   "warranty_order",
//   "gift_order",
//   "show_role",
//   "create_role",
//   "update_role",
//   "delete_role",
//   "list_role",
//   "show_car",
//   "create_car",
//   "update_car",
//   "delete_car",
//   "list_car",
//   "show_position",
//   "create_position",
//   "update_position",
//   "delete_position",
//   "list_position",
//   "show_referral",
//   "create_referral",
//   "update_referral",
//   "delete_referral",
//   "list_referral",
//   "show_suppliers",
//   "create_suppliers",
//   "update_suppliers",
//   "delete_suppliers",
//   "list_suppliers",
//   "show_wharehouse",
//   "create_wharehouse",
//   "update_wharehouse",
//   "delete_wharehouse",
//   "list_wharehouse",
//   "list_purchase",
//   "create_purchase",
//   "update_purchase",
//   "show_purchase",
//   "delete_purchase",
//   "list_purchase_item",
//   "create_purchase_item",
//   "update_purchase_item",
//   "delete_purchase_item",
//   "pending_purchase",
//   "approve_purchase",
//   "reject_purchase",
//   "complete_purchase",
//   "list_intenal_purchase",
//   "create_intenal_purchase",
//   "update_intenal_purchase",
//   "show_intenal_purchase",
//   "delete_intenal_purchase",
//   "list_intenal_purchase_item",
//   "create_intenal_purchase_item",
//   "update_intenal_purchase_item",
//   "delete_intenal_purchase_item",
//   "pending_intenal_purchase",
//   "approve_intenal_purchase",
//   "reject_intenal_purchase",
//   "complete_intenal_purchase",
//   "list_transfer",
//   "create_transfer",
//   "update_transfer",
//   "show_transfer",
//   "delete_transfer",
//   "list_transfer_item",
//   "create_transfer_item",
//   "update_transfer_item",
//   "delete_transfer_item",
//   "pending_transfer",
//   "approve_transfer",
//   "reject_transfer",
//   "list_transfer_receive",
//   "update_transfer_receive",
//   "show_transfer_receive",
//   "delete_transfer_receive",
//   "list_transfer_receive_item",
//   "create_transfer_receive_item",
//   "update_transfer_receive_item",
//   "delete_transfer_receive_item",
//   "receive_transfer_receive",
//   "close_transfer_receive",



// NEWWWW 
//   "create_suppliers",
//   "update_suppliers",
//   "delete_suppliers",
//   "list_suppliers",
//   "show_wharehouse",
//   "create_wharehouse",
//   "update_wharehouse",
//   "delete_wharehouse",
//   "list_wharehouse",
//   "list_purchase",
//   "create_purchase",
//   "update_purchase",
//   "show_purchase",
//   "delete_purchase",
//   "list_purchase_item",
//   "create_purchase_item",
//   "update_purchase_item",
//   "delete_purchase_item",
//   "pending_purchase",
//   "approve_purchase",
//   "reject_purchase",
//   "complete_purchase",
//   "list_intenal_purchase",
//   "create_intenal_purchase",
//   "update_intenal_purchase",
//   "show_intenal_purchase",
//   "delete_intenal_purchase",
//   "list_intenal_purchase_item",
//   "create_intenal_purchase_item",
//   "update_intenal_purchase_item",
//   "delete_intenal_purchase_item",
//   "pending_intenal_purchase",
//   "approve_intenal_purchase",
//   "reject_intenal_purchase",
//   "complete_intenal_purchase",
//   "list_transfer",
//   "create_transfer",
//   "update_transfer",
//   "show_transfer",
//   "delete_transfer",
//   "list_transfer_item",
//   "create_transfer_item",
//   "update_transfer_item",
//   "delete_transfer_item",
//   "pending_transfer",
//   "approve_transfer",
//   "reject_transfer",
//   "list_transfer_receive",
//   "update_transfer_receive",
//   "show_transfer_receive",
//   "delete_transfer_receive",
//   "list_transfer_receive_item",
//   "create_transfer_receive_item",
//   "update_transfer_receive_item",
//   "delete_transfer_receive_item",
//   "receive_transfer_receive",
//   "close_transfer_receive"
// 